/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ca.mcgill.ecse.divesafe.application;

import java.sql.Date;
import java.util.ArrayList;
import java.util.List;
import ca.mcgill.ecse.divesafe.controller.BundleController;
import ca.mcgill.ecse.divesafe.controller.EquipmentController;
import ca.mcgill.ecse.divesafe.controller.MemberController;
import ca.mcgill.ecse.divesafe.controller.SetupController;
import ca.mcgill.ecse.divesafe.javafx.fxml.DiveSafeFxmlView;
import ca.mcgill.ecse.divesafe.model.DiveSafe;
import ca.mcgill.ecse.divesafe.persistence.DiveSafePersistence;
import javafx.application.Application;

public class DiveSafeApplication {
  
  public static final boolean DARK_MODE = true;
  private static DiveSafe diveSafe;

  /**
   * Main entry point
   * @author Shidan Javaheri
   * @param args
   */
  public static void main(String[] args) {
    
   Application.launch(DiveSafeFxmlView.class,args); 
   
  }
  /**
   * Load the Json file into the DiveSafeObject when it is requested, if it is null
   * @author Shidan Javaheri
   *
   */
  public static DiveSafe getDiveSafe() {
    if (diveSafe == null) {
      // if diveSafe is null, load json file
      diveSafe = DiveSafePersistence.load(); 
    }
    
    return diveSafe;
  }
}
